---
output:
    html_document: default
css: /Users/user/local_depend/style_sheets/style.css
---
## Hello (2, 封面)

<div class="red">
先講**副標題**: Progress through technology

Hello 這個字出現在 19 世紀。  
它的前身有**很多型態**  
造成它的型態統一成 Hello 一個字跟電話的發明及普及有關  
所以作者才會下 Progress through technology 這副標題
</div>

## H-words (3)

<div class="red">

Hello 的前身  
是許多**發音類似**、**H 開頭**的字組成  
這些 H 開頭的字有**兩種用途**:

**(1)**  
最*早是用來 **呼喊**、吸引他人注意


**(2)**  
H 開頭的字用在**打招呼**則之後才出現
</div>

-----------------------------------

1. Catch each other’s attention
    - **Hey**, **Ho**: 13th century

    - **Hi**: 15th century

    - **Hollo**, **Hillo**, **Holla**, **Halloo**: 16th century
        - Shouts used in hunting


2. Greetings
    - **Hal**: Be healthy
 
    - **Hail**: 13th century


## *Hello* (4)

<div class="red">

**(1, 1-1)**  
因為 Hello 這個字早期用在**打招呼**或**呼喊**  
它的**文字拼法**在當初並未統一  
Hello 裡面的"e", 可任意替換成 a, e, i, o, u 五種母音

**(2)**   
Google Ngram viewer:  
資料來自 Google Books 電子書中 1800 - 2008 出版的書

</div>

---------------------------------

1. Spelling Difference
    1. Hallo, Hello, Hillo, Hollo, Hullo  
[Stress was on the second syllable, difficult to hear the quality of the first vowel.]{.gray}


    2. Google Ngram Viewer (5 spellings)


## How *Hello* became Popular (5)

<div class="red">

**(1, 2)**  
Hello 之所以成為現在通行的用法  
是因為電話的發明  

這裡**岔題**一下  
書中說電話是 愛迪生 發明的是**錯**的,  愛迪生是**改良電話**  

發明電話的是**貝爾**,  美國 AT&T 公司的創辦人

**(3)**  
電話發明之後  
大家在接電話時需要一個**發語詞**  告訴對方我有在聽  

**(4)**  
一開始有各式各樣的發語詞  
但因為**愛迪生**偏好使用 Hello,  Hello 才逐漸成為**主流**  

譬如說愛迪生在**測試留聲機**的時候大喊 Hello  
他也在一封信中使用 Hello, **母音為 e **的拼法

</div>
--------------------------------

1. Early 1800s: informal, street slang

2. **Telephone**
    - 1876: Invented by *Alexander Graham Bell* (Not *Edison*)

3. Need a way of starting a conversation

4. **Thomas Edison**
    - Prefered Hello:  
[Shouted 'Hello' ('Halloo') into the mouthpiece when testing a phonograph (留聲機)]{.gray}
    
    - A letter (1877) used **Hello**:  
["I don't think we shall need a call bell, as 'Hello!' can be heard 10 to 20 feet away. What do you think?"]{.gray}


## Bell & Edison (6)

Photo of Bell(左) & Edison(右)


## Hello Girls (7)

- Photo of Hello Girls (電話接線生)


## *Hi* (8)

<div class="red">

跟 Hello 有關 Hi 出現在 **19 世紀的美國**  

**(1)**  
在世界各地,  Hi 的使用比起 Hello **更為廣泛**  
Hi 因為**書寫方便**更常出現在 **Email**中, 在**年輕人**中也更常使用  

所以作者指出 Hi 可能在**未來取代 Hello**

**(2)**  
Google Ngram: 比較 Hi, Hello

</div>

--------------------------------------

- USA: 19th century

- Widely spread

1. Replace Hello?
    - Common in Email
    - Easier to type than 'Hello'

2. Google ngram: Hi vs. Hello


## Disinterested (9, 封面)

<div class="red">
在講 disinterested 之前  
要先從這個字的**來源**開始。
</div>

## Interest (名詞) (10)

<div class="red">

**(1)**  
Interest 在 **15 世紀**出現時, 只有**名詞**的用法  
意義依據出現時間, 依序為**擁有權**, **股份**, **好處與利益**  

**(2)**  
直到 **17 世紀**才出現**興趣**、**嗜好**的意義
</div>


1. 15th Century
    - 擁有權  
    [have an interest in an estate]{.gray}
    
    - 股份  
    [hold an interest in a company]{.gray}
    
    - 好處、利益  
    [It’s in your interest to vote for me]{.gray}

2. 17th Century: 興趣、嗜好


## Interested (形容詞) (11)

<div class="red">
Mermaid Plot: 名詞, 形容詞 演變
</div>

## **Dis-** vs. **Un-** (12)

<div class="red">

Interested 出現之後  
自然而然就會有**否定**型式的出現  

英文中形容詞的否定型態  
通常是加上 **Dis** 或 **Un**  
但**很少**會兩種都存在 

**(1, 2)**  
例如:

**(3, 4)**  
Interested 有趣的地方在於  
其**兩種否定形式**皆存在  
而且*有時候*可以代表**相同的意思**
</div>


1. **Dis-** only
    - Discontent vs. ~~Uncontent~~

2. **Un-** only
    - ~~Discomfortable~~ vs. Uncomfortable

3. **Dis-** & **Un-** with different meanings
    - Disterested vs. Uninterested

4. **Dis-** & **Un-** with overlapping meanings
    - Disterested vs. Uninterested


## History: **Dis**interested vs. **Un**interested (13)

<div class="red">
其實 Disinterested 和 Uninterested 的意思  
在*歷史*上有很**複雜的關係**  

Disinterested 在 **17 世紀**剛出現時  
是**沒興趣**、**莫不關心**的意思  
之後**轉變為公正的意思**

Uninterested 則比較晚出現  
*意義轉變的方式*正好**與 Disinterested 相反**

**(1)**  
所以在 **18 世紀中期** 的時候  
這兩個字的用法完全重疊
</div>

Plot: 意義轉變

- **1750**: Meanings completely overlap


## Modern: **Dis**interested vs. **Un**interested (14)

<div class="red">
到了*現代*, 這兩個字延續過去的意思  

**(1)**  
**Un**interested 指**無聊的**, **莫不關心的**  

**(2)**  
**Dis**interesed 指**公正的**  
然後, 雖然牛津字典說 Disinterested 不可以用來指**無聊的**  

但在英國, Disinterested 有 **25%** 的部分被用來指**無聊的**  
美國則有 50%
<div>


1. Uninterested: bored, unconcerned 

2. Disinterested: impartial, bored('incorrect', [Oxford](https://en.oxforddictionaries.com/usage/disinterested-or-uninterested){target="_blank"})


Pie chart: Meaning of **disinterested** in US, UK


## Dragsman (15)

<div class="red">
接下來要講的  
是社會中**特定族群**的用語  
書中是舉**小偷**和**強盜**的用語為例子
</div>

## *A Dictionary of the Slang and Cant Languages* (16)

<div class="red">
19 世紀

</div>

- George Andrewes, 1809

- (Hope to) Make it easier to detect crimes  
書頁圖


## Dragsman (17)

<div class="red">
Dragsman 今日已很少在使用
</div>

- Drag (18th 世紀): Horse-drawn wagon

1. 馬車圖

2. Dragsman
    1. 車夫
    2. one who stole goods or luggage from vehicles





## Cant Languages still used today (18)

- footpad: one who robs pedestrians

- water-pad: One who robs ships

- coiner: 偽造貨幣者


## 臺灣黑話 (19)

- 吃土豆 (閩南語)?

- 食品藥物管理署: 毒品相關術語


## 毒品術語 (使用) (20)

- 常見: 嗑藥, 拉 K
- 生動: 走水路(靜脈注射), 螞蟻蛋(高純度)


## 毒品術語 (交易) (21)

- 運轉手
- 海角七號