---
title: "語言與性別"
subtitle: "一對中年夫婦的對話"
author: "廖永賦"
date: June 7, 2018
output:
  ioslides_presentation:
    widescreen: true
    css: presentation_style.css
    incremental: false
    transition: 0.6
    logo: tux.svg
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, comment="")
library(widgetframe)
knitr::opts_chunk$set(widgetframe_self_contained = FALSE) 
knitr::opts_chunk$set(widgetframe_isolate_widgets = TRUE) 
knitr::opts_chunk$set(widgetframe_widgets_dir = 'widgets' )
```

背景
---------------------

- 對話主角：我的父母
    - 父親：57歲
    - 母親：55歲

- 地點：家裡客廳

- 時間：22:30 左右

- 錄音長度：1 分 49 秒

- 話題背景：父親上午處理祖母的房子買賣，和母親談論到房仲業者。


錄音檔
----------------------------------

<iframe src="https://drive.google.com/file/d/1rgyKmlQu0aW_5w4r6X8WVF1xqEwlAgmt/preview" width="640" height="480"></iframe>

[錄音](https://drive.google.com/file/d/1rgyKmlQu0aW_5w4r6X8WVF1xqEwlAgmt/view?usp=sharing){.small}

表格
--------------------

```{r}
library(dplyr)
dad <- readr::read_table2("duration.txt", col_names = FALSE)[1, ] %>% unlist() %>% unname()
dad <- dad[!is.na(dad)]

mom<- readr::read_table2("duration.txt", col_names = FALSE)[3, ] %>% unlist() %>% unname()
mom<- mom[!is.na(mom)]
```

```{r}
df <- data.frame(
    ident = c("父","母"),
    total_duration = c(sum(dad), sum(mom)),
    counts = c(length(dad), length(mom))
) %>% 
    mutate(avg_dur = 
               (total_duration/counts) %>% round(2))
    #mutate(interrupt = c(0,1)) 
knitr::kable(df, format = "markdown", align = "c",
             col.names =
                 c("身份","總長度(秒)","說話(次)",
              "平均長度(秒)")             
              )
```

<br>
[說話者轉換次數：12]{.grey}

圖
-------------------------------------
```{r fig.show='hold', out.width="30%", fig.dim=c(3,4)}
library(ggplot2)
lab_bar <- function(y) labs(x="", fill="", y="", title=y)
ggplot(df) +
    geom_bar(aes(x=ident, y=total_duration, fill=ident), 
             stat = "identity")+ 
             scale_y_continuous(breaks=seq(0,70,10))+
             lab_bar("總長度(秒)")

ggplot(df) +
    geom_bar(aes(x=ident, y=counts, fill=ident), 
             stat = "identity")+ lab_bar("次數")

ggplot(df) +
    geom_bar(aes(x=ident, y=avg_dur, fill=ident), 
             stat = "identity")+ lab_bar("平均長度(秒)")
```

[說話者轉換次數：12]{.grey}


討論(此錄音)
---------------------------------

- 父親
    - 話多(時間是母親的 3.5 倍)
    - 陳述、回答為主
    - 佔話題主動、支配地位
- 母親
    - 話少且短(每句話平均時間較短)
    - 提問為主
    - 聆聽、資訊接受者
- 原因：對話主題造成？
    - 父親掌握話題主導權
    - 父親握有話題相關資訊(講述他的經歷)

討論(日常對話){.small}
---------------------------------

- 父親
    - 話多(長度長)：對母親、姐姐、我、外人皆成立
    - 喜歡掌握話題、說話時常居**主導地位**
- 母親
    - 與父親對話時，常居於**被動**、**資訊接收者**
        - 主題非日常涉獵範圍、沒興趣
        - 例外：
            - 主題為「財經」、「股票」等(共同興趣)：說話時間、主動程度上升
            - 主題為「保險」(母親行業)：居主導地位

討論(與讀本比較){.columns-2 .small}
---------------------------------

|    |      公共場合     |      私人場合     |
|:--:|:-----------------:|:-----------------:|
| 男 | 話多 / 報告式談話 |        話少       |
| 女 |        話少       | 話多 / 情感式談話 |

<br>

- 報告式談話：
    - > [男人]展示自己高人一等的知識與才能，就著說故事、說笑話以及提供資訊等方式，將自己推向舞台的中心 &nbsp;&nbsp;  ---《男女親密對話》p.70

<br><br>

- 父親
    - 偏好報告式談話
    - 公、私場合：皆話多、偏好報告式談話
- 母親：無法歸類於表格中
    - 報告式、情感式談話：無偏好差別
    - 公、私場合上無差異

