---
layout: post
title: 我的R語言學習歷程
key: 20180127
tags:
- R
- Course
- experience
- 中文
---
<!--more-->

接觸 **R** 的時間大約五個月了，從原本對電腦、程式一竅不通到現在能有效率的 debug 、寫出簡潔有條理的 R code 、甚至用 R 與 Markdown 架站寫部落格。算一算，我每週通常至少 3 天會用到 R ，不是督促自己熟悉 R ，是因為它太有魅力了。我現在只要有作業沒有要求使用Word，幾乎都會用 Rmarkdown 或 Markdown 去完成，再輸出成 PDF 或 html ，因為總忍不住要碰一下 R 。

學 R 語言很有趣[^I1]，但也相當耗時耗力。我在學習 R 上花了大量的時間，若不是因緣際會找到對的方向，我不可能花費那麼多力氣去學 R ，甚至可能直接放棄。雖然如此，我還是感到有點可惜，若能更早知道有效率的學習方式，我就不必花費如此大量的時間(以及大量的紙張)。因此，我希望將學習 R 的心路歷程寫下，說明為何我可以持續學習而未放棄，以及若從頭來過，我會挑選哪些學習資源，讓學習可以更有效率。

為何我能持續學習 R 而未放棄？其實現在我比較頭大的問題是：**要怎麼克制自己不要一直打開 Rstudio ？**正是因為我學 R 的過程如同打電動一樣歡樂，所以**放棄**這個問題根本不存在。事實上，剛開始學 R 時並不怎麼歡樂，直到上了學校的課(見下[課程回顧](#course))才越來越喜歡 R 。

## 課程回顧： R 語言與資料科學導論{#course}

106學年上學期，我最喜歡、也意外收穫最多的課是謝舒凱老師開設的 [R 語言與資料科學導論](https://nol2.aca.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=142%20U0750&class=&dpt_code=1420&ser_no=76601&semester=106-1&lang=CH)，或許會是我大學生涯最喜歡的課吧。

起初是抱著學好 R 語言(加上通識快修不完)的心情去加簽這門課的，但課堂上 R 語言的語法卻教得不多。然正是這種**不聚焦在程式語法的課程安排**，讓我把 R 學得非常好。如果課程從頭到尾都在教 R 語言，到期末我一定會受不了越顯複雜的語法[^a]，最後便隨意敷衍了事。我在這門課收穫最大的，反而不是課堂學到的技巧，而是老師、助教們傳達的一些概念與想法，以及自己探索這些概念想法的樂趣與收穫：

- R的生態圈[^1]以及 Open Source 的概念

- 資料科學與 Story telling: **Coding** 於資料科學中的角色不同於其在工程上的角色，亦及 Aesthetic Coding 與 Functional Coding 的概念。資料科學不僅包含傳統的 Functional Coding，也包含大量的 Aesthetic Coding，用於傳達資料科學上的發現

- Reproducibility: [Rmarkdown](http://rmarkdown.rstudio.com/) (`.Rmd`) 是我見過最強大的文件格式，可以輸出成網頁、投影片、PDF、Word、Markdown 等。這讓使用者可以在一份文件中做事情(`Rmd`)，並依據所需輸出成各種文件，而不用剪剪貼貼(從Word貼到 PPT)，也省下排版花費的心力。例如，要報告可輸出成投影片、要列印可輸出成PDF、要放到網路上可輸出成網頁。這讓使用者能有效率的管理與記錄工作流程，是達到 [Reproducibility](https://en.wikipedia.org/wiki/Reproducibility) 的基礎。

- 文本分析: 我本來對這部分最沒有興趣，直到我意識到文本資料是研究人類行為、社會與文化最重要的資料來源之一[^2]^,^[^3]

### 課程起手式{#start}

這門課與我個性相符，完全顯現在第一堂課實習課(Lab Session)的作業上。作業與R並無相關，而是要使用Markdown格式撰寫自我介紹。由於我對簡約風有點痴迷[^sim] (受 Markdown 影響後更為痴迷)，我便在 Markdown 上花了一些時間。目前，透過R與 Pandoc Markdown 的整合，我可以用 Rmarkdown 簡潔快速地寫出含有上下標、Footnotes、超連結、citation等等的文件[^md] (不須使用html語法)，我甚至未來考慮使用Rmarkdown撰寫論文。

對Rmarkdown的痴迷與熱愛可說是我R語言功力進步的關鍵。**Rmarkdown賦予每個人將自己的想法傳達給其他人的能力**[^idea]，因此，**能將美好的事物以及想法與大家分享**成為我學習 R 最強烈的動機。例如，當初在做這門課的[期末專案](https://rlads2017g1.github.io/taiwan.github.io/presentation.html)時，發覺 R 可以畫出各種[互動式圖表](http://gallery.htmlwidgets.org/)，於是我開始尋找最適合呈現資料的方式。由於不同種類的圖，有時需要不同格式的資料[^dt]，因此為了畫出最適合的圖，我反覆整理許多資料以符合格式要求，使得我 data-wrangling 的能力大幅提升。



markdown Rmarkdown data-wrangling webpage





[^I1]: **R 語言**本身不算有趣，而是 R 及其生態圈所能做到的事。幾乎任何想得到、可用電腦處理的事情，都可找到相關的 R 套件。

[^a]: 我在開學前的暑假即開始自學 **R**，進步相當緩慢，而且語法時常忘記。最重要的是，我必須花心力督促自己才能繼續。開學後在課堂上教導的內容不多，僅做些簡單的介紹，剩下的要靠自己發掘。由於深深感受到 Markdown 的潛力(見[課程起手式](#start)，我開始「不務正業」，去學一些和 R (看似)不怎麼相關的東西(例如，研究如何用 GitHub Pages 架部落格)，也越來越喜歡 html 格式(以前偏愛 PDF，但發現 html 能呈現的東西比 PDF 多太多，又比較美觀)。於是，R 成為我處理作業最常使用的程式之一。

[^1]: 我常在想，不知到何時 **SAS** 與 **SPSS** 會被 **R** 幹掉

[^2]: 至少是資訊量最大的資料來源，比較看看社群網站、網路、書籍(見 [Google Ngram](https://en.wikipedia.org/wiki/Google_Ngram_Viewer)，體驗一下文本資料的強大)累積的資料量與心理學實驗累積的資料量

[^3]: 語言學不僅可用於研究語言、還可拿來當作研究人類社會與文化的工具

[^sim]: 我本來對美感、簡約、使用者經驗完全不在乎，但受我最好的朋友的影響，越來越在意這些東西(看到乾淨舒服的版面就會很爽，有點點不和諧就會想修改它)

[^md]: 見 [Rmarkdown](http://rmarkdown.rstudio.com/) 了解其強大

[^idea]: Markdown 的學習門檻很低，使大家能簡單地寫出排版整潔漂亮的文章。Rmarkdown 大幅擴充 Markdown 的功能，秉持著相同的精神，Rmarkdown 使大家能簡單地寫出排版整潔漂亮(且含有R跑出之圖表)的**文章**、**投影片**、**書籍**，甚至**網站**

[^dt]: 例如欲繪製時間序列的資料`ggplot2`及`dygraphs`對資料就有不同的要求