---
title: "Time series workflow"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

```{r, message=FALSE, warning=FALSE, comment=FALSE}
library(readr)
library(dplyr)
library(lubridate)
library(tidyr)
```


```{r, message=FALSE, warning=FALSE, comment=FALSE}
mers_Korea <- read_csv("./mers_Korea.csv") %>%
    rename("date"=`[hide]Date`, "cum_case"=`Cases*1*2`, "cum_death"=`Deaths*2`)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
kable(mers_Korea, format="markdown", align="c")
```


from strings to date format
```{r, message=FALSE, warning=FALSE}
mers_Korea <- mers_Korea %>%    
    mutate(date=dmy(mers_Korea$date)) %>%
    filter(date!=is.na(mers_Korea$date)) %>%
    mutate(case=lead(cum_case)-cum_case) %>%
    mutate(death=lead(cum_death)-cum_death) %>%
    replace_na(list(case=0, death=0)) %>%
    mutate(month=month(date)) %>%
    select(month, date, case, death, everything()) 
        ## reorder columns, everything() selects the rest variables
        ## (order uoy don't care)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
kable(mers_Korea, format="markdown", align="c")
```


case per day to case per month
```{r, message=FALSE, warning=FALSE}
mers_month <- mers_Korea %>%
    mutate(month_date=as.Date(paste0("2015-",mers_Korea$month,"-28"),"%Y-%m-%d")) %>%   # pick a (common) date to represent month, e.g. y-m-28 
    group_by(month_date) %>%
    summarise(month_case=sum(case), month_death=sum(death))

# or use a function
YMD <- function(x){paste('2015',x,'-28',sep="")}
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
kable(mers_month, format="markdown", align="c")
```
