---
title: "Model"
output: 
    html_document:
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE,comment="")
knitr::opts_knit$set(root.dir='..') # set root directory
library(readr)
library(ggplot2)
```

```{r}
plot <- function (file) {
    fluc <- read_delim(file, "\t",escape_double = FALSE, trim_ws = TRUE)
    fluc <- fluc[seq(1,length(fluc$time), 100),] # speed up: plot only every 10 data points from the original data
    
    ggplot(data=fluc,mapping = aes(x=time))+
        geom_line(mapping = aes(y=N1,color="Sex"))+
        geom_line(mapping = aes(y=N2,color="Asex"))+
        geom_line(mapping = aes(y=Pr1,color="Prey 1"),linetype = "dotdash")+
        geom_line(mapping = aes(y=Pr2,color="Prey 2"),linetype = "dotdash")+
        labs(x="Time", y="Abundance", color="")+
        theme_gray()+
        scale_x_continuous(breaks = seq(0,as.integer(fluc$time[nrow(fluc)]), 100))
}
```

## Equations for Modeling
$${{d}\over{d\,t}}\,N_{1} =\left[ b_{1} N_{1}\,\left( S_{2}\,c_{12}+S_{1}\,c_{11}\right)- d_{1} N_{1}\, \right]  \label{eq:N1}$$

$${{d}\over{d\,t}}\, N_{2}  =\left[ b_{2} N_{2}\,\left(
 S_{2}\,c_{22}+S_{1}\,c_{21}\right)- d_{2} N_{2}\, \right]  \label{eq:N2}$$

$${{d}\over{d\,t}}\, S_{1}  =\left[ a_{1} S_{1}\,\,\left(
 1-{{S_{1}}\over{k_{1}}}\right)-S_{1}\,\left(N_{2}\,c_{21}+N_{1}\,c_{
 11}\right) \right] \label{eq:s1}$$

$${{d}\over{d\,t}}\, S_{2}  =\left[ a_{2} S_{2}\,\,\left(
 1-{{S_{2}}\over{k_{2}}}\right)-S_{2}\,\left(N_{2}\,c_{22}+N_{1}\,c_{
 12}\right) \right] \label{eq:s2}$$

- $N_i$ : Population size of Predator $i$.
    
    - $i=1: Sex$
    
    - $i=2: Asex$

- $S_j$ : Population size of Prey $j$

## Original Parameters
```c
double c11= 0.25; // consumption matrix parameter
double c12= 0.25; // consumption matrix parameter
double c21= 0.0; // consumption matrix parameter
double c22= 0.5; // consumption matrix parameter

double k1_g= 1; // carrying capacity of prey 1: good year
double k2_g= 1; // carrying capacity of prey 2: good year
```

```{r echo=FALSE}
plot("./data/origin.txt")
```


## No Spatial Structure

$C=\pmatrix{c_{11}&c_{12}\cr c_{21}&c_{22}\cr }$ have entries all equal to some number, i.e. $\alpha_{12}=\alpha_{21}=1$ in competition equations.

```c
double c11= 0.25; // consumption matrix parameter
double c12= 0.25; // consumption matrix parameter
double c21= 0.25; // consumption matrix parameter
double c22= 0.25; // consumption matrix parameter

double k1_g= 1; // carrying capacity of prey 1: good year
double k2_g= 1; // carrying capacity of prey 2: good year
```

```{r}
plot("./data/no_spatial.txt")
```

------------------

<br>

## With Fluctuation

Set $rate=0.5$

- $rate=0$: No fluctuation

- $rate=1$: Good, Harsh year alternate

### Original Parameters

```c
double k1_g= 1; // carrying capacity of prey 1: good year
double k2_g= 1; // carrying capacity of prey 2: good year
double k1_h= 0.3; // carrying capacity of prey 1: harsh year
double k2_h= 0.3; // carrying capacity of prey 2: harsh year
```
```{r}
plot("./data/origin_fluc.txt")
```

### No Spatial Structure

```{r}
plot("./data/no_spatial_fluc.txt")
```
